# Generated by Django 2.0.3 on 2018-03-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer_generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files_pdf/')),
            ],
        ),
        migrations.DeleteModel(
            name='ProfileImage',
        ),
    ]
